package dao;

import java.util.List;
import model.Goods;
import model.GoodsExample;
import model.Page;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Goods> selectByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Goods selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Goods record);

	List<Goods> findByMingcheng(int index, String mingcheng);

	Integer countByMingcheng(String mingcheng);
}