package dao;

import java.util.List;
import model.Huiyuan;
import model.HuiyuanExample;
import org.apache.ibatis.annotations.Param;

public interface HuiyuanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(HuiyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(HuiyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Huiyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Huiyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Huiyuan> selectByExample(HuiyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Huiyuan selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Huiyuan record, @Param("example") HuiyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Huiyuan record, @Param("example") HuiyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Huiyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_huiyuan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Huiyuan record);
}