package dao;

import java.util.List;
import model.Leibie;
import model.LeibieExample;
import org.apache.ibatis.annotations.Param;

public interface LeibieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(LeibieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(LeibieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Leibie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Leibie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Leibie> selectByExample(LeibieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Leibie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Leibie record, @Param("example") LeibieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Leibie record, @Param("example") LeibieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Leibie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_leibie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Leibie record);
}