package dao;

import java.util.List;
import model.Liuyuan;
import model.LiuyuanExample;
import org.apache.ibatis.annotations.Param;

public interface LiuyuanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(LiuyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(LiuyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Liuyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Liuyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Liuyuan> selectByExample(LiuyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Liuyuan selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Liuyuan record, @Param("example") LiuyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Liuyuan record, @Param("example") LiuyuanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Liuyuan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_liuyan
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Liuyuan record);
}