package dao;

import java.util.List;
import model.Mingxi;
import model.MingxiExample;
import org.apache.ibatis.annotations.Param;

public interface MingxiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(MingxiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(MingxiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Mingxi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Mingxi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Mingxi> selectByExample(MingxiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Mingxi selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Mingxi record, @Param("example") MingxiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Mingxi record, @Param("example") MingxiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Mingxi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mingxi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Mingxi record);
}