package dao;

import java.util.List;
import model.Pingjia;
import model.PingjiaExample;
import org.apache.ibatis.annotations.Param;

public interface PingjiaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	long countByExample(PingjiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByExample(PingjiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insert(Pingjia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int insertSelective(Pingjia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	List<Pingjia> selectByExample(PingjiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	Pingjia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Pingjia record, @Param("example") PingjiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByExample(@Param("record") Pingjia record, @Param("example") PingjiaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKeySelective(Pingjia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	int updateByPrimaryKey(Pingjia record);
}