package model;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_admin.userId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_admin.userName
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_admin.userPw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String userpw;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_admin.userId
	 * @return  the value of t_admin.userId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_admin.userId
	 * @param userid  the value for t_admin.userId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_admin.userName
	 * @return  the value of t_admin.userName
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_admin.userName
	 * @param username  the value for t_admin.userName
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_admin.userPw
	 * @return  the value of t_admin.userPw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getUserpw() {
		return userpw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_admin.userPw
	 * @param userpw  the value for t_admin.userPw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setUserpw(String userpw) {
		this.userpw = userpw;
	}
}