package model;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.leibieId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer leibieid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String mingcheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.jieshao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String jieshao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.fujian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String fujian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.jiage
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer jiage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.tejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer tejia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.shifoutejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String shifoutejia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String del;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.id
	 * @return  the value of t_goods.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.id
	 * @param id  the value for t_goods.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.leibieId
	 * @return  the value of t_goods.leibieId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getLeibieid() {
		return leibieid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.leibieId
	 * @param leibieid  the value for t_goods.leibieId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setLeibieid(Integer leibieid) {
		this.leibieid = leibieid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.mingcheng
	 * @return  the value of t_goods.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getMingcheng() {
		return mingcheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.mingcheng
	 * @param mingcheng  the value for t_goods.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setMingcheng(String mingcheng) {
		this.mingcheng = mingcheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.jieshao
	 * @return  the value of t_goods.jieshao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getJieshao() {
		return jieshao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.jieshao
	 * @param jieshao  the value for t_goods.jieshao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setJieshao(String jieshao) {
		this.jieshao = jieshao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.fujian
	 * @return  the value of t_goods.fujian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getFujian() {
		return fujian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.fujian
	 * @param fujian  the value for t_goods.fujian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.jiage
	 * @return  the value of t_goods.jiage
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getJiage() {
		return jiage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.jiage
	 * @param jiage  the value for t_goods.jiage
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setJiage(Integer jiage) {
		this.jiage = jiage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.tejia
	 * @return  the value of t_goods.tejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getTejia() {
		return tejia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.tejia
	 * @param tejia  the value for t_goods.tejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setTejia(Integer tejia) {
		this.tejia = tejia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.shifoutejia
	 * @return  the value of t_goods.shifoutejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getShifoutejia() {
		return shifoutejia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.shifoutejia
	 * @param shifoutejia  the value for t_goods.shifoutejia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setShifoutejia(String shifoutejia) {
		this.shifoutejia = shifoutejia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.del
	 * @return  the value of t_goods.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.del
	 * @param del  the value for t_goods.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDel(String del) {
		this.del = del;
	}

	private int index;
	private int totalPage;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public int getTotalPage() {
		return totalPage;
	}

	public void setTotalPage(int totalPage) {
		this.totalPage = totalPage;
	}
}