package model;

public class Huiyuan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.loginname
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.loginpw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String loginpw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String xingming;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.xingbie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String xingbie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.nianling
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String nianling;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.address
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String dianhua;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.leixing
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String leixing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_huiyuan.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String del;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.id
	 * @return  the value of t_huiyuan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.id
	 * @param id  the value for t_huiyuan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.loginname
	 * @return  the value of t_huiyuan.loginname
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.loginname
	 * @param loginname  the value for t_huiyuan.loginname
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.loginpw
	 * @return  the value of t_huiyuan.loginpw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getLoginpw() {
		return loginpw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.loginpw
	 * @param loginpw  the value for t_huiyuan.loginpw
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setLoginpw(String loginpw) {
		this.loginpw = loginpw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.xingming
	 * @return  the value of t_huiyuan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getXingming() {
		return xingming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.xingming
	 * @param xingming  the value for t_huiyuan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setXingming(String xingming) {
		this.xingming = xingming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.xingbie
	 * @return  the value of t_huiyuan.xingbie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getXingbie() {
		return xingbie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.xingbie
	 * @param xingbie  the value for t_huiyuan.xingbie
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setXingbie(String xingbie) {
		this.xingbie = xingbie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.nianling
	 * @return  the value of t_huiyuan.nianling
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getNianling() {
		return nianling;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.nianling
	 * @param nianling  the value for t_huiyuan.nianling
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setNianling(String nianling) {
		this.nianling = nianling;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.address
	 * @return  the value of t_huiyuan.address
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.address
	 * @param address  the value for t_huiyuan.address
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.dianhua
	 * @return  the value of t_huiyuan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getDianhua() {
		return dianhua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.dianhua
	 * @param dianhua  the value for t_huiyuan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDianhua(String dianhua) {
		this.dianhua = dianhua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.leixing
	 * @return  the value of t_huiyuan.leixing
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getLeixing() {
		return leixing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.leixing
	 * @param leixing  the value for t_huiyuan.leixing
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setLeixing(String leixing) {
		this.leixing = leixing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_huiyuan.del
	 * @return  the value of t_huiyuan.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_huiyuan.del
	 * @param del  the value for t_huiyuan.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDel(String del) {
		this.del = del;
	}
}