package model;

public class Leibie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leibie.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leibie.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String mingcheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_leibie.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String del;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leibie.id
	 * @return  the value of t_leibie.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leibie.id
	 * @param id  the value for t_leibie.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leibie.mingcheng
	 * @return  the value of t_leibie.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getMingcheng() {
		return mingcheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leibie.mingcheng
	 * @param mingcheng  the value for t_leibie.mingcheng
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setMingcheng(String mingcheng) {
		this.mingcheng = mingcheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_leibie.del
	 * @return  the value of t_leibie.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_leibie.del
	 * @param del  the value for t_leibie.del
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDel(String del) {
		this.del = del;
	}
}