package model;

public class Liuyuan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String xingming;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.zuzhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String zuzhi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String dianhua;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.youxiang
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String youxiang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String neirong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_liuyan.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String shijian;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.id
	 * @return  the value of t_liuyan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.id
	 * @param id  the value for t_liuyan.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.xingming
	 * @return  the value of t_liuyan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getXingming() {
		return xingming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.xingming
	 * @param xingming  the value for t_liuyan.xingming
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setXingming(String xingming) {
		this.xingming = xingming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.zuzhi
	 * @return  the value of t_liuyan.zuzhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getZuzhi() {
		return zuzhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.zuzhi
	 * @param zuzhi  the value for t_liuyan.zuzhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setZuzhi(String zuzhi) {
		this.zuzhi = zuzhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.dianhua
	 * @return  the value of t_liuyan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getDianhua() {
		return dianhua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.dianhua
	 * @param dianhua  the value for t_liuyan.dianhua
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDianhua(String dianhua) {
		this.dianhua = dianhua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.youxiang
	 * @return  the value of t_liuyan.youxiang
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getYouxiang() {
		return youxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.youxiang
	 * @param youxiang  the value for t_liuyan.youxiang
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setYouxiang(String youxiang) {
		this.youxiang = youxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.neirong
	 * @return  the value of t_liuyan.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getNeirong() {
		return neirong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.neirong
	 * @param neirong  the value for t_liuyan.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setNeirong(String neirong) {
		this.neirong = neirong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_liuyan.shijian
	 * @return  the value of t_liuyan.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getShijian() {
		return shijian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_liuyan.shijian
	 * @param shijian  the value for t_liuyan.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setShijian(String shijian) {
		this.shijian = shijian;
	}
}