package model;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBianhaoIsNull() {
			addCriterion("bianhao is null");
			return (Criteria) this;
		}

		public Criteria andBianhaoIsNotNull() {
			addCriterion("bianhao is not null");
			return (Criteria) this;
		}

		public Criteria andBianhaoEqualTo(String value) {
			addCriterion("bianhao =", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoNotEqualTo(String value) {
			addCriterion("bianhao <>", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoGreaterThan(String value) {
			addCriterion("bianhao >", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoGreaterThanOrEqualTo(String value) {
			addCriterion("bianhao >=", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoLessThan(String value) {
			addCriterion("bianhao <", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoLessThanOrEqualTo(String value) {
			addCriterion("bianhao <=", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoLike(String value) {
			addCriterion("bianhao like", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoNotLike(String value) {
			addCriterion("bianhao not like", value, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoIn(List<String> values) {
			addCriterion("bianhao in", values, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoNotIn(List<String> values) {
			addCriterion("bianhao not in", values, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoBetween(String value1, String value2) {
			addCriterion("bianhao between", value1, value2, "bianhao");
			return (Criteria) this;
		}

		public Criteria andBianhaoNotBetween(String value1, String value2) {
			addCriterion("bianhao not between", value1, value2, "bianhao");
			return (Criteria) this;
		}

		public Criteria andXiadanshiIsNull() {
			addCriterion("xiadanshi is null");
			return (Criteria) this;
		}

		public Criteria andXiadanshiIsNotNull() {
			addCriterion("xiadanshi is not null");
			return (Criteria) this;
		}

		public Criteria andXiadanshiEqualTo(String value) {
			addCriterion("xiadanshi =", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiNotEqualTo(String value) {
			addCriterion("xiadanshi <>", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiGreaterThan(String value) {
			addCriterion("xiadanshi >", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiGreaterThanOrEqualTo(String value) {
			addCriterion("xiadanshi >=", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiLessThan(String value) {
			addCriterion("xiadanshi <", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiLessThanOrEqualTo(String value) {
			addCriterion("xiadanshi <=", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiLike(String value) {
			addCriterion("xiadanshi like", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiNotLike(String value) {
			addCriterion("xiadanshi not like", value, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiIn(List<String> values) {
			addCriterion("xiadanshi in", values, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiNotIn(List<String> values) {
			addCriterion("xiadanshi not in", values, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiBetween(String value1, String value2) {
			addCriterion("xiadanshi between", value1, value2, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andXiadanshiNotBetween(String value1, String value2) {
			addCriterion("xiadanshi not between", value1, value2, "xiadanshi");
			return (Criteria) this;
		}

		public Criteria andZtIsNull() {
			addCriterion("zt is null");
			return (Criteria) this;
		}

		public Criteria andZtIsNotNull() {
			addCriterion("zt is not null");
			return (Criteria) this;
		}

		public Criteria andZtEqualTo(String value) {
			addCriterion("zt =", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtNotEqualTo(String value) {
			addCriterion("zt <>", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtGreaterThan(String value) {
			addCriterion("zt >", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtGreaterThanOrEqualTo(String value) {
			addCriterion("zt >=", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtLessThan(String value) {
			addCriterion("zt <", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtLessThanOrEqualTo(String value) {
			addCriterion("zt <=", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtLike(String value) {
			addCriterion("zt like", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtNotLike(String value) {
			addCriterion("zt not like", value, "zt");
			return (Criteria) this;
		}

		public Criteria andZtIn(List<String> values) {
			addCriterion("zt in", values, "zt");
			return (Criteria) this;
		}

		public Criteria andZtNotIn(List<String> values) {
			addCriterion("zt not in", values, "zt");
			return (Criteria) this;
		}

		public Criteria andZtBetween(String value1, String value2) {
			addCriterion("zt between", value1, value2, "zt");
			return (Criteria) this;
		}

		public Criteria andZtNotBetween(String value1, String value2) {
			addCriterion("zt not between", value1, value2, "zt");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiIsNull() {
			addCriterion("songhuodizhi is null");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiIsNotNull() {
			addCriterion("songhuodizhi is not null");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiEqualTo(String value) {
			addCriterion("songhuodizhi =", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiNotEqualTo(String value) {
			addCriterion("songhuodizhi <>", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiGreaterThan(String value) {
			addCriterion("songhuodizhi >", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiGreaterThanOrEqualTo(String value) {
			addCriterion("songhuodizhi >=", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiLessThan(String value) {
			addCriterion("songhuodizhi <", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiLessThanOrEqualTo(String value) {
			addCriterion("songhuodizhi <=", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiLike(String value) {
			addCriterion("songhuodizhi like", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiNotLike(String value) {
			addCriterion("songhuodizhi not like", value, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiIn(List<String> values) {
			addCriterion("songhuodizhi in", values, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiNotIn(List<String> values) {
			addCriterion("songhuodizhi not in", values, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiBetween(String value1, String value2) {
			addCriterion("songhuodizhi between", value1, value2, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andSonghuodizhiNotBetween(String value1, String value2) {
			addCriterion("songhuodizhi not between", value1, value2, "songhuodizhi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiIsNull() {
			addCriterion("fukuanfangshi is null");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiIsNotNull() {
			addCriterion("fukuanfangshi is not null");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiEqualTo(String value) {
			addCriterion("fukuanfangshi =", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiNotEqualTo(String value) {
			addCriterion("fukuanfangshi <>", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiGreaterThan(String value) {
			addCriterion("fukuanfangshi >", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiGreaterThanOrEqualTo(String value) {
			addCriterion("fukuanfangshi >=", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiLessThan(String value) {
			addCriterion("fukuanfangshi <", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiLessThanOrEqualTo(String value) {
			addCriterion("fukuanfangshi <=", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiLike(String value) {
			addCriterion("fukuanfangshi like", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiNotLike(String value) {
			addCriterion("fukuanfangshi not like", value, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiIn(List<String> values) {
			addCriterion("fukuanfangshi in", values, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiNotIn(List<String> values) {
			addCriterion("fukuanfangshi not in", values, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiBetween(String value1, String value2) {
			addCriterion("fukuanfangshi between", value1, value2, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andFukuanfangshiNotBetween(String value1, String value2) {
			addCriterion("fukuanfangshi not between", value1, value2, "fukuanfangshi");
			return (Criteria) this;
		}

		public Criteria andZongjiaIsNull() {
			addCriterion("zongjia is null");
			return (Criteria) this;
		}

		public Criteria andZongjiaIsNotNull() {
			addCriterion("zongjia is not null");
			return (Criteria) this;
		}

		public Criteria andZongjiaEqualTo(Integer value) {
			addCriterion("zongjia =", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaNotEqualTo(Integer value) {
			addCriterion("zongjia <>", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaGreaterThan(Integer value) {
			addCriterion("zongjia >", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaGreaterThanOrEqualTo(Integer value) {
			addCriterion("zongjia >=", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaLessThan(Integer value) {
			addCriterion("zongjia <", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaLessThanOrEqualTo(Integer value) {
			addCriterion("zongjia <=", value, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaIn(List<Integer> values) {
			addCriterion("zongjia in", values, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaNotIn(List<Integer> values) {
			addCriterion("zongjia not in", values, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaBetween(Integer value1, Integer value2) {
			addCriterion("zongjia between", value1, value2, "zongjia");
			return (Criteria) this;
		}

		public Criteria andZongjiaNotBetween(Integer value1, Integer value2) {
			addCriterion("zongjia not between", value1, value2, "zongjia");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidIsNull() {
			addCriterion("huiyuanId is null");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidIsNotNull() {
			addCriterion("huiyuanId is not null");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidEqualTo(Integer value) {
			addCriterion("huiyuanId =", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidNotEqualTo(Integer value) {
			addCriterion("huiyuanId <>", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidGreaterThan(Integer value) {
			addCriterion("huiyuanId >", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidGreaterThanOrEqualTo(Integer value) {
			addCriterion("huiyuanId >=", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidLessThan(Integer value) {
			addCriterion("huiyuanId <", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidLessThanOrEqualTo(Integer value) {
			addCriterion("huiyuanId <=", value, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidIn(List<Integer> values) {
			addCriterion("huiyuanId in", values, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidNotIn(List<Integer> values) {
			addCriterion("huiyuanId not in", values, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidBetween(Integer value1, Integer value2) {
			addCriterion("huiyuanId between", value1, value2, "huiyuanid");
			return (Criteria) this;
		}

		public Criteria andHuiyuanidNotBetween(Integer value1, Integer value2) {
			addCriterion("huiyuanId not between", value1, value2, "huiyuanid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 10 15:56:59 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}