package model;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bianhao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String bianhao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.xiadanshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String xiadanshi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.zt
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String zt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.songhuodizhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String songhuodizhi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.fukuanfangshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String fukuanfangshi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.zongjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer zongjia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.huiyuanId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer huiyuanid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.id
	 * @return  the value of t_order.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.id
	 * @param id  the value for t_order.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bianhao
	 * @return  the value of t_order.bianhao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getBianhao() {
		return bianhao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bianhao
	 * @param bianhao  the value for t_order.bianhao
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.xiadanshi
	 * @return  the value of t_order.xiadanshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getXiadanshi() {
		return xiadanshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.xiadanshi
	 * @param xiadanshi  the value for t_order.xiadanshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setXiadanshi(String xiadanshi) {
		this.xiadanshi = xiadanshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.zt
	 * @return  the value of t_order.zt
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getZt() {
		return zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.zt
	 * @param zt  the value for t_order.zt
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setZt(String zt) {
		this.zt = zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.songhuodizhi
	 * @return  the value of t_order.songhuodizhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getSonghuodizhi() {
		return songhuodizhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.songhuodizhi
	 * @param songhuodizhi  the value for t_order.songhuodizhi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setSonghuodizhi(String songhuodizhi) {
		this.songhuodizhi = songhuodizhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.fukuanfangshi
	 * @return  the value of t_order.fukuanfangshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getFukuanfangshi() {
		return fukuanfangshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.fukuanfangshi
	 * @param fukuanfangshi  the value for t_order.fukuanfangshi
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setFukuanfangshi(String fukuanfangshi) {
		this.fukuanfangshi = fukuanfangshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.zongjia
	 * @return  the value of t_order.zongjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getZongjia() {
		return zongjia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.zongjia
	 * @param zongjia  the value for t_order.zongjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setZongjia(Integer zongjia) {
		this.zongjia = zongjia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.huiyuanId
	 * @return  the value of t_order.huiyuanId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getHuiyuanid() {
		return huiyuanid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.huiyuanId
	 * @param huiyuanid  the value for t_order.huiyuanId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setHuiyuanid(Integer huiyuanid) {
		this.huiyuanid = huiyuanid;
	}
}