package model;

import java.util.ArrayList;
import java.util.List;

public class PingjiaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public PingjiaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNeirongIsNull() {
			addCriterion("neirong is null");
			return (Criteria) this;
		}

		public Criteria andNeirongIsNotNull() {
			addCriterion("neirong is not null");
			return (Criteria) this;
		}

		public Criteria andNeirongEqualTo(String value) {
			addCriterion("neirong =", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongNotEqualTo(String value) {
			addCriterion("neirong <>", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongGreaterThan(String value) {
			addCriterion("neirong >", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongGreaterThanOrEqualTo(String value) {
			addCriterion("neirong >=", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongLessThan(String value) {
			addCriterion("neirong <", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongLessThanOrEqualTo(String value) {
			addCriterion("neirong <=", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongLike(String value) {
			addCriterion("neirong like", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongNotLike(String value) {
			addCriterion("neirong not like", value, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongIn(List<String> values) {
			addCriterion("neirong in", values, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongNotIn(List<String> values) {
			addCriterion("neirong not in", values, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongBetween(String value1, String value2) {
			addCriterion("neirong between", value1, value2, "neirong");
			return (Criteria) this;
		}

		public Criteria andNeirongNotBetween(String value1, String value2) {
			addCriterion("neirong not between", value1, value2, "neirong");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNull() {
			addCriterion("goodsId is null");
			return (Criteria) this;
		}

		public Criteria andGoodsidIsNotNull() {
			addCriterion("goodsId is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsidEqualTo(String value) {
			addCriterion("goodsId =", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotEqualTo(String value) {
			addCriterion("goodsId <>", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidGreaterThan(String value) {
			addCriterion("goodsId >", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidGreaterThanOrEqualTo(String value) {
			addCriterion("goodsId >=", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidLessThan(String value) {
			addCriterion("goodsId <", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidLessThanOrEqualTo(String value) {
			addCriterion("goodsId <=", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidLike(String value) {
			addCriterion("goodsId like", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotLike(String value) {
			addCriterion("goodsId not like", value, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidIn(List<String> values) {
			addCriterion("goodsId in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotIn(List<String> values) {
			addCriterion("goodsId not in", values, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidBetween(String value1, String value2) {
			addCriterion("goodsId between", value1, value2, "goodsid");
			return (Criteria) this;
		}

		public Criteria andGoodsidNotBetween(String value1, String value2) {
			addCriterion("goodsId not between", value1, value2, "goodsid");
			return (Criteria) this;
		}

		public Criteria andShijianIsNull() {
			addCriterion("shijian is null");
			return (Criteria) this;
		}

		public Criteria andShijianIsNotNull() {
			addCriterion("shijian is not null");
			return (Criteria) this;
		}

		public Criteria andShijianEqualTo(String value) {
			addCriterion("shijian =", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianNotEqualTo(String value) {
			addCriterion("shijian <>", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianGreaterThan(String value) {
			addCriterion("shijian >", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianGreaterThanOrEqualTo(String value) {
			addCriterion("shijian >=", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianLessThan(String value) {
			addCriterion("shijian <", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianLessThanOrEqualTo(String value) {
			addCriterion("shijian <=", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianLike(String value) {
			addCriterion("shijian like", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianNotLike(String value) {
			addCriterion("shijian not like", value, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianIn(List<String> values) {
			addCriterion("shijian in", values, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianNotIn(List<String> values) {
			addCriterion("shijian not in", values, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianBetween(String value1, String value2) {
			addCriterion("shijian between", value1, value2, "shijian");
			return (Criteria) this;
		}

		public Criteria andShijianNotBetween(String value1, String value2) {
			addCriterion("shijian not between", value1, value2, "shijian");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_pingjia
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pingjia
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 10 15:56:59 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}