package model;

public class Pingjia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pingjia.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pingjia.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String neirong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pingjia.goodsId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_pingjia.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	private String shijian;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pingjia.id
	 * @return  the value of t_pingjia.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pingjia.id
	 * @param id  the value for t_pingjia.id
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pingjia.neirong
	 * @return  the value of t_pingjia.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getNeirong() {
		return neirong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pingjia.neirong
	 * @param neirong  the value for t_pingjia.neirong
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setNeirong(String neirong) {
		this.neirong = neirong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pingjia.goodsId
	 * @return  the value of t_pingjia.goodsId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pingjia.goodsId
	 * @param goodsid  the value for t_pingjia.goodsId
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setGoodsid(String goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_pingjia.shijian
	 * @return  the value of t_pingjia.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public String getShijian() {
		return shijian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_pingjia.shijian
	 * @param shijian  the value for t_pingjia.shijian
	 * @mbg.generated  Wed Apr 10 15:57:18 CST 2019
	 */
	public void setShijian(String shijian) {
		this.shijian = shijian;
	}
}